### ISSUE TITLE
Add ability to show/hide MOTD

### ISSUE THREAD

**Issue by mattroseman** [destinygg/chat-gui#136]
I was a little annoyed because there was a MOTD in DGG that had dates in it when Destiny was on vacation, but I deleted the message and immediately lost the dates.

I think it would be nice if instead of removing the MOTD entirely it was toggleable in some way.

I wrote a quick [Tampermonkey script](https://gist.github.com/mattroseman/80e3113db46d385183fd0e062c28dc58) to fix the issue for me; it's janky but gives you an idea of what I was thinking.

https://user-images.githubusercontent.com/6654122/216841109-b0238340-f96d-4118-8f67-d340ec122baa.mov

**Comment by vyneer** [comment]
Hey there! Thanks for the suggestion <3
I think the version of chat in prod is a bit behind the latest one, I added a "show dismissed pin" button in [this](https://github.com/destinygg/chat-gui/pull/119) PR a couple of days ago.
So it should be available soon 😄
