### ISSUE TITLE
Chat focus adds transparency to pinned message

### ISSUE THREAD

**Issue by Riott** [destinygg/chat-gui#195]
I've noticed when you focus other chatters or flairs the pinned message also becomes transparent, I'm unsure if this is intended behaviour or not.

![image](https://user-images.githubusercontent.com/1808209/226423218-d701ff1e-f504-4213-9b7c-7d3739b45eb4.png)

**Comment by 11k** [comment]
Nope, not intentional and I think the better behavior is always keeping it visible. Thanks!
