### ISSUE TITLE
Not typing the color in all lowercase when tagging a user tags them with the default color

### ISSUE THREAD

**Issue by 11k** [destinygg/chat-gui#305]
![image](https://github.com/destinygg/chat-gui/assets/20373896/3f10e08b-f95c-4da9-908f-902283b0eeeb)

**Comment by bilalshaikh292** [comment]
heyy @11k is the issue still open I would like to contribute?

**Comment by 11k** [comment]
> heyy @11k is the issue still open I would like to contribute?

Absolutely, go for it!
