### ISSUE TITLE
An extra newline can appear in a message when the embed icon is positioned at the very edge of the chat

### ISSUE THREAD

**Issue by 11k** [destinygg/chat-gui#313]
![q6AynLv](https://github.com/destinygg/chat-gui/assets/20373896/f3ba7a5e-172f-4bee-95a7-0c9d8538dc2d)

**Comment by Riott** [comment]
I cannot recreate this, I looked up the original message and it looks like maybe the emote didn't load? 
![image](https://github.com/destinygg/chat-gui/assets/1808209/94203654-37d9-4337-bb4c-304c47bf14ee)
when I type the same message I get the emote fine? 
![image](https://github.com/destinygg/chat-gui/assets/1808209/4b9d9ca7-af28-4ffa-9692-d9b5f656c883)

**Comment by 11k** [comment]
I also resized chat a bunch and wasn't able to reproduce. I think it's safe to say it wrapped because of the emote and it just didn't render for the user who brought it to my attention.

The emote not rendering is a separate matter that we can think about later. 😅
