### ISSUE TITLE
Shortened links in the user mini-menu resolve to the shortened broken text as seen.

### ISSUE THREAD

**Issue by xmif** [destinygg/chat-gui#479]
Example:
![image](https://github.com/destinygg/chat-gui/assets/127546972/29af9d07-3ff0-4522-bb49-6a9875ce321e)

Top link hover/click:
![image](https://github.com/destinygg/chat-gui/assets/127546972/ee0fb8ba-3ae8-4a84-961e-8e96ba092098)

Bottom link hover/click:
![image](https://github.com/destinygg/chat-gui/assets/127546972/7ee0ae64-bd76-459e-9be9-3c7e9ad013d9)

Link used in the example screenshots: [clicky!](https://preview.redd.it/ot5oxfh57k3d1.jpeg?width=762&format=pjpg&auto=webp&s=4abc388ede9ae2ae26441adde2be32f2b8f1be36) - links that get shortened seem to behave the same, could be reproduced on both Firefox and Chromium (Edge).

**Comment by reda777** [comment]
This line in the file "assets/chat/js/menus/ChatUserInfoMenu.js" 

`const msg = MessageBuilder.message(text, new ChatUser(nick));`  I think `MessageBuilder.message()` is supposed to take the text that the user types, but the generated message for the floating menu uses the text from the chat containing the shortened link.

Either remove this part of the code and just copy the div node from the chat, or change the `href` value to the correct one.
