### ISSUE TITLE
Tooltip takes too long to appear when hovering emotes and badges

### ISSUE THREAD

**Issue by jpacitto** [destinygg/chat-gui#81]
When chat is flying by the time it takes to hover on an emote for the tooltip to appear takes way too long.

Would be great if tooltip was displayed instantly on hover.

**Comment by 11k** [comment]
I can see this as being a little annoying if you leave your mouse cursor over the chat, so I think what we'll do instead is require a left click to bring up the tooltip. We've always wanted to display the creator when hovering over an emote, so this can be part of that change.
